### ISSUE TITLE
__HOTLOAD__ is not defined

### ISSUE THREAD

**Issue by jlengstorf** [panteliselef/astro-with-clerk-auth#154]
I'm trying to integrate this into a site and I'm getting an error. I'm using 0.6.8. I didn't have any luck figuring out what was going on with a quick glance at the source.

Here's my code: https://github.com/learnwithjason/netflix-style-astro-app/commit/9c28d462f4153e002418ac852eabe0691d0a7239

```
ReferenceError: __HOTLOAD__ is not defined
    at Object.start (/Users/blitz/github/learnwithjason/netflix-style-astro-app/node_modules/astro-clerk-auth/src/server/index.ts:307:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by panteliselef** [comment]
Hey @jlengstorf thanks for reporting. I see that you are using the netlify adapter, that is a setup i have not tried myself, so i will investigate.

Do you mind sharing if you are receiving this while building or running the dev server ?

**Comment by jlengstorf** [comment]
hey, had a chance to dig into this more. whatever was happening is not happening anymore, so I suspect I may have borked my node_modules or something. closing as I'm pretty sure this was on my end, not yours
