### ISSUE TITLE
Sign In Page Redirects To Factor One Page

### ISSUE THREAD

**Issue by slackermorris** [panteliselef/astro-with-clerk-auth#168]
Hi there,

**Context**

Thanks a bunch for this SDK. 

I am at a loss to best describe what my issue is, mostly because the ready-to-use _magic_ of Clerk sometimes makes it difficult to know what needs to be configured manually. And, to be honest, I've hit so many set backs elsewhere that I and a bit deflated and am hoping for an answer that doesn't require me to scale Everest myself for the understanding. Lol. Yes, I am being lazy, but something about "save time here to spend it elsewhere".

Whenever I try to sign-in using the `SignIn` component I am redirected to a `factor-one` page (which I have not implemented). I would have thought that the `SignIn` component would handle password authentication for me, etc, so I am unsure what I need to do? Any clues?

![image](https://github.com/panteliselef/astro-with-clerk-auth/assets/35620369/617e35b7-65e5-4548-815f-00baa7fd4a4b)

**Relevant Files**

```json
// package.json
"astro-clerk-auth": "^0.7.0"
```

```javascript
// astro.config.mjs

import { defineConfig } from "astro/config";
import tailwind from "@astrojs/tailwind";
import glsl from "vite-plugin-glsl";
import aws from "astro-sst";

import react from "@astrojs/react";
import clerk from "astro-clerk-auth";

export default defineConfig({
  output: "server",
  site: "https://www.badreviewsmakegoodmovies.com",
  adapter: aws(),
  integrations: [
    tailwind({
      applyBaseStyles: false,
    }),
    react(),
    clerk({
      afterSignInUrl: "/",
      afterSignUpUrl: "/",
    }),
  ],
  vite: {
    plugins: [glsl()],
  },
});
```

```astro
// sign-in.astro
---
import { ClerkLayout } from "astro-clerk-auth/components/control";
import { SignIn } from "astro-clerk-auth/components/react";
import Layout from "../layouts/Layout.astro";


---

<ClerkLayout >
  <Layout title="Sign In to Clerk + Astro">
    <div>
      <SignIn path="/sign-in"/>
    </div>
  </Layout>
</ClerkLayout>
```

**Comment by panteliselef** [comment]
Hey @slackermorris, Let's try something quick can u do this ?

```tsx
<SignIn routing="hash" />
```

**Comment by slackermorris** [comment]
@panteliselef Yup that solved it just fine. I'm not too versed in routing. Would you mind explaining how the above solution has fixed my issue?

**Comment by panteliselef** [comment]
Here is that [the official docs](https://clerk.com/docs/guides/routing#routing-in-clerk) say about routing in Clerk components.

I recommend hash routing because astro performs full page loads and components with path routing will flash in the screen as a whole new document loads.

Probably the issue with your original code was that the `/sign-in` route was not a [catch all route](https://docs.astro.build/en/guides/routing/#rest-parameters)

**Comment by panteliselef** [comment]
I'll be closing this as the issue seems to have been resolved.
